apps/foro/urls.py
from django.urls import path

from . import views

app_name = "foro"

urlpatterns = [
     # post
     path("submit/post/",
          views.PostSubmit.as_view(),
          name="submit_post"),
     path("r/<str:subreddit>/post/create/",
          views.PostCreateView.as_view(),
          name="subreddit_post_create"),
     path("r/<str:subreddit>/post/<int:year>/<int:month>/<int:day>/<slug:post>/",
          views.PostDetailView.as_view(),
          name="subreddit_post_detail"),
     path('post/like/',
          views.PostLike.as_view(),
          name='post_like'),

     # subreddit
     path("subreddit/create/",
          views.SubredditCreateView.as_view(),
          name="subreddit_create"),
     path("subreddit/r/<str:name>/",
          views.SubredditDetailView.as_view(),
          name="subreddit_detail"),

     # comment
     path("subreddit/post/comment-json/",
          views.CommentCreateListView.as_view(),
          name="comment_json"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("", include("apps.pages.urls", namespace="pages")),
    path("foro/", include("apps.foro.urls", namespace="foro")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/foro/forms.py
from django import forms
from django.utils.text import slugify
from ckeditor.widgets import CKEditorWidget

from .models import Subreddit, Post, Comment


# Every letter to Capitalize(charfield)
class Capitalize(forms.CharField):
    def to_python(self, value):
        return value.capitalize()


class SubredditForm(forms.ModelForm):
    name = forms.CharField(max_length=21,
                           widget=forms.TextInput(attrs={
                            'class': 'block w-full px-4 py-3 text-sm text-gray-700 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40 dark:border-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:focus:border-blue-300',
                            'placeholder': 'r/'}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(SubredditForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Subreddit
        fields = ('name', )

    def clean_name(self):
        name = self.cleaned_data.get('name')
        name = ''.join(name.split())
        if Subreddit.objects.filter(name__iexact=name).exists():
            msg = "Ese nombre ya esta en uso"
            raise forms.ValidationError(msg)
        return name

    def save(self, commit=True):
        subreddit = super().save(commit=False)
        name = ''.join(subreddit.name.split())
        subreddit.name = name
        subreddit.slug = slugify(subreddit.name)
        subreddit.created_by = self.user
        if commit:
            subreddit.save()
        return subreddit


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
                                                   'class': 'rounded-lg  flex-1 appearance-none border border-gray-700 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent',
                                                   'placeholder': 'Title'}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.subreddit = kwargs.pop('subreddit', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Post
        fields = ('title', 'body')

    def save(self, commit=True):
        post = super().save(commit=False)
        post.slug = slugify(post.title)
        post.subreddit = self.subreddit
        post.author = self.user
        if commit:
            post.save()
        return post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

apps/foro/views.py
from django.urls import reverse
from django.http import JsonResponse
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Value
from django.db.models.functions import Coalesce
from django.conf import settings


from .models import Post, Subreddit, Comment
from .forms import SubredditForm, PostForm, CommentForm


class PostDetailView(View):
    def get(self, request, post, year, month, day, **kwargs):
        post = get_object_or_404(Post,
                                 slug=post,
                                 publish__year=year,
                                 publish__month=month,
                                 publish__day=day)

        # List of active comments for this post
        comments = post.comments.filter(active=True)

        # Form for users to comment
        form = CommentForm()
        context = {
            'post': post,
            'form': form,
            'comments': comments
        }
        return render(request, 'foro/post/detail.html', context)


class CommentCreateListView(View):
    def post(self, request, *args, **kwargs):
        response = {}
        try:
            post_slug = request.POST.get('slug')
            comment_parent = request.POST.get('parent')
            print(comment_parent)
            # print(int(comment_parent))
            post = Post.objects.get(slug=post_slug)
            action = request.POST.get('action')
            if action == 'create_comment':
                # create comment
                form = CommentForm(request.POST)
                if form.is_valid():
                    comment = form.save(commit=False)
                    comment.author = request.user
                    comment.post = post
                    if comment_parent:
                        comment.parent = Comment.objects \
                                                .get(id=comment_parent)
                    comment.save()
                    response['status'] = 'ok'
                else:
                    response['status'] = 'error'
                    print(form.errors)
            else:
                # List of active comments for this post
                data = [i.toJSON() for i in post.comments.filter(active=True)]
                response['data'] = data
        except Post.DoesNotExist:
            response['error'] = 'Post does not exist'
        except Exception as e:
            print(str(e))
            response['error'] = 'Unexpected error'
        # else:
        #     response['error'] = 'Invalid option'
        return JsonResponse(response)


class PostListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts': posts,
        }
        return render(request, 'foro/post/list.html', context)


class PostCreateView(View):
    def get(self, request, subreddit):
        subreddit = get_object_or_404(Subreddit,
                                      name=subreddit)
        subreddits = Subreddit.objects.all()

        form = PostForm(user=request.user,
                        subreddit=subreddit)
        disabled = None
        context = {
            'form': form,
            'subreddit': subreddit,
            'subreddits': subreddits,
            'disabled': disabled,
        }
        return render(request, 'foro/post/create.html', context)

    def post(self, request, subreddit):
        subreddit = get_object_or_404(Subreddit,
                                      name=subreddit)
        subreddits = Subreddit.objects.all()
        form = PostForm(request.POST,
                        user=request.user,
                        subreddit=subreddit)
        if form.is_valid():
            post = form.save()
            return redirect(reverse('foro:subreddit_detail',
                                    args=[post.subreddit.name]))
        disabled = None
        context = {
            'form': form,
            'subreddit': subreddit,
            'subreddits': subreddits,
            'disabled': disabled,
        }
        return render(request, 'foro/post/create.html', context)


class PostSubmit(View):
    def get(self, request):
        form = PostForm()
        subreddits = Subreddit.objects.all()
        disabled = True
        context = {
            'form': form,
            'subreddits': subreddits,
            'disabled': disabled
        }
        return render(request, 'foro/post/create.html', context)

class PostLike(View):
    def post(self, request, *args, **kwargs):
        post_slug = request.POST.get('slug')
        action = request.POST.get('action')
        like_exists = None
        dislike_exists = None
        if post_slug and action:
            try:
                post = Post.objects.get(slug=post_slug)
                user_like = post.users_like \
                                .filter(pk=request.user.pk) \
                                .exists()
                user_dislike = post.users_dislike \
                                   .filter(pk=request.user.pk) \
                                   .exists()
                if action == 'like':
                    if user_dislike:
                        post.users_like.add(request.user)
                        post.users_dislike.remove(request.user)
                        like_exists = True
                        dislike_exists = False
                    else:
                        if user_like:
                            post.users_like.remove(request.user)
                            like_exists = False
                            dislike_exists = False
                        else:
                            post.users_like.add(request.user)
                            like_exists = True
                            dislike_exists = False
                else:
                    if user_like:
                        post.users_dislike.add(request.user)
                        post.users_like.remove(request.user)
                        like_exists = False
                        dislike_exists = True
                    else:
                        if user_dislike:
                            post.users_dislike.remove(request.user)
                            like_exists = False
                            dislike_exists = False
                        else:
                            post.users_dislike.add(request.user)
                            like_exists = False
                            dislike_exists = True
                return JsonResponse({'status': 'ok',
                                     'likes': post.users_like.count(),
                                     'like_exists': like_exists,
                                     'dislike_exists': dislike_exists,
                                     'dislikes': post.users_dislike.count()})
            except Post.DoesNotExist:
                pass
        return JsonResponse({'status': 'error'})


@method_decorator(require_POST, name='dispatch')
class SubredditCreateView(LoginRequiredMixin, View):
    # def get(self, request, *args, **kwargs):
    #     form = SubredditForm(user=request.user)
    #     context = {
    #         'form': form,
    #     }
    #     return render(request, 'foro/subreddit/create.html', context)

    def post(self, request, *args, **kwargs):
        form = SubredditForm(request.POST, user=request.user)
        if form.is_valid():
            subreddit = form.save()
            return redirect(reverse('foro:subreddit_detail', args=[subreddit.name]))
        # context = {
        #     'form': form,
        # }
        return redirect('pages:home')


class SubredditDetailView(View):
    def get(self, request, name):
        subreddit = Subreddit.objects.get(name=name)
        context = {
            'subreddit': subreddit,
        }
        return render(request, 'foro/subreddit/detail.html', context)

templates/foro/post/create.html
{% extends 'base.html' %} 
{% load static %}

{% block title %} {{ subreddit.name }} {% endblock title %}

{% block content %}
<div 
x-data = "{open: false}"
class="relative inline-block text-left">
  <div>
    <button 
    @click = "open = true"
    type="button" class="inline-flex w-full justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" id="menu-button" aria-expanded="true" aria-haspopup="true">
      Select Community
      <svg class="-mr-1 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
      </svg>
    </button>
  </div>

  <div 
  x-show="open"
  @click.away = "open = false"
  class="absolute right-0 z-40 mt-2 w-72 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
    <div class="py-1 overflow-y-auto h-96" role="none">
      <span class="text-sm text-gray-400 px-4">your profile</span>
      <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
      {% for sub in subreddits  %}
        <a href="{% url 'foro:subreddit_post_create' sub %}" class="flex items-center text-gray-700 px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
          <div class="flex-shrink-0">
            <img
              class="h-10 w-10 rounded-full"
              src="{{ sub.get_image_url }}"
              alt=""
            />
          </div>
          <div class="ml-2">
            r/{{ sub.name }}
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
</div>

  <div class="mt-4">
    <h1 class="sr-only">Recent questions</h1>
    <form action="." method="post">
         {% csrf_token %}
        <div class="bg-white px-4 py-6 shadow sm:p-6 sm:rounded-lg space-y-3">
          <div class="relative">
            {{ form.title }}
          </div>
            {{ form.media }}
            {{ form.body }}

            <div class="w-full px-4 pb-4 ml-auto text-gray-500 ">
                <div class="flex items-center justify-end space-x-2">
                    <!-- <button type="button" class="py-2 px-4  boder border-blue-700 bg-white hover:bg-gray-50 focus:ring-blue-500 focus:ring-offset-blue-200 text-blue-700 w-md transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-full ">
                        Save draft
                    </button> -->
                    <button type="submit" {% if disabled %} disabled {% endif %} class="py-2 px-4 {% if disabled %} bg-gray-800 hover:bg-gray-800 focus:ring-gray-600 {% else %} bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 {% endif %}  focus:ring-offset-blue-200 text-white w-md transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-full ">
                        Post
                    </button>
                </div>
            </div>
        </div>
    </form>
  </div>
{% endblock content %}


{% block right_section %}
{% if not disabled %}
  <section aria-labelledby="who-to-follow-heading">
    <div class="bg-white rounded-lg shadow">
        <div class="flex items-center justify-between rounded-t-lg py-4 px-3 w-full bg-sky-700">
            <h2
            id="who-to-follow-heading"
            class="text-base font-bold text-white"
          >
            About Community
          </h2>

            <div
          x-data="{ isOpen: false }"
          x-init="init()"
          @keydown.escape.stop="isOpen = false"
          @click.away="isOpen = false"
          class="relative inline-block text-left"
        >
          <div>
            <button
              type="button"
              class="-m-2 p-2 rounded-full flex items-center text-gray-400 hover:text-gray-600"
              id="options-menu-0-button"
              x-ref="button"
              @click="isOpen = !isOpen"
              @keyup.space.prevent="isOpen = true"
              @keydown.enter.prevent="isOpen = true"
              aria-expanded="false"
              aria-haspopup="true"
              x-bind:aria-expanded="open.toString()"
            >
              <span class="sr-only">Open options</span>
              <svg
                class="h-5 w-5"
                x-description="Heroicon name: solid/dots-vertical"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                aria-hidden="true"
              >
                <path
                  d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"
                ></path>
              </svg>
            </button>
          </div>

          <div
            x-show="isOpen"
            x-transition:enter="transition ease-out duration-100"
            x-transition:enter-start="transform opacity-0 scale-95"
            x-transition:enter-end="transform opacity-100 scale-100"
            x-transition:leave="transition ease-in duration-75"
            x-transition:leave-start="transform opacity-100 scale-100"
            x-transition:leave-end="transform opacity-0 scale-95"
            class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
            x-ref="menu-items"
            x-description="Dropdown menu, show/hide based on menu state."
            x-bind:aria-activedescendant="activeDescendant"
            role="menu"
            aria-orientation="vertical"
            aria-labelledby="options-menu-0-button"
            tabindex="-1"
            @keydown.tab="isOpen = false"
            @keydown.enter.prevent="isOpen = false"
            @keyup.space.prevent="isOpen = false"
          >
            <div class="py-1" role="none">
              <a
                href="#"
                class="text-gray-700 flex px-4 py-2 text-sm"
                role="menuitem"
                tabindex="-1"
                id="options-menu-0-item-0"
                @click="isOpen = false"
              >
                <svg
                  class="mr-3 h-5 w-5 text-gray-400"
                  x-description="Heroicon name: solid/star"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  aria-hidden="true"
                >
                  <path
                    d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                  ></path>
                </svg>
                <span>Add to favorites</span>
              </a>
              <a
                href="#"
                class="text-gray-700 flex px-4 py-2 text-sm"
                role="menuitem"
                tabindex="-1"
                id="options-menu-0-item-1"
                @click="isOpen = false"
              >
                <svg
                  class="mr-3 h-5 w-5 text-gray-400"
                  x-description="Heroicon name: solid/code"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  aria-hidden="true"
                >
                  <path
                    fill-rule="evenodd"
                    d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
                <span>Embed</span>
              </a>
              <a
                href="#"
                class="text-gray-700 flex px-4 py-2 text-sm"
                role="menuitem"
                tabindex="-1"
                id="options-menu-0-item-2"
                @click="isOpen = false"
              >
                <svg
                  class="mr-3 h-5 w-5 text-gray-400"
                  x-description="Heroicon name: solid/flag"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  aria-hidden="true"
                >
                  <path
                    fill-rule="evenodd"
                    d="M3 6a3 3 0 013-3h10a1 1 0 01.8 1.6L14.25 8l2.55 3.4A1 1 0 0116 13H6a1 1 0 00-1 1v3a1 1 0 11-2 0V6z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
                <span>Report content</span>
              </a>
            </div>
          </div>
            </div>
        </div>
      <div class="p-6 ">
        <div class="flex items-center space-x-3">
            <div class="flex-shrink-0">
              <img
                class="h-14 w-14 rounded-full"
                {% if post.subreddit.image %}
                  src="{{ post.subreddit.image.url  }}"
                {% else %}
                  src="{% static 'img/default-thumbnail.jpg' %}"
                {% endif %}
                alt=""
              />
            </div>
            <div class="min-w-0 flex-1">
              <p class="text-sm font-semibold text-gray-900">
                <a href="#" class="hover:underline">
                  <time datetime="2020-12-09T11:43:00">
                    <!-- December 9 at 11:43 AM -->
                   r/{{ subreddit.name }} 
                  </time
                  >
                </a>
              </p>
            </div>
            <div class="flex-shrink-0 self-center flex">
     
            </div>
        </div>

        <div>

            <p class="text-sm font-medium text-gray-900">
                <!-- December 9 at 11:43 AM -->
            {{ subreddit.description|safe }} 
            </p>
        </div>
        <!-- <div class="flex items-center py-4 space-x-3">
            <div class="flex-shrink-0">
              <img
                class="h-8 w-8 rounded-full"
                src="https://images.unsplash.com/photo-1519345182560-3f2917c472ef?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=2&amp;w=256&amp;h=256&amp;q=80"
                alt=""
              />
            </div>
            <div class="min-w-0 flex-1">
              <p class="text-sm font-medium text-gray-900">
                <a href="#">Leonard Krasner</a>
              </p>
              <p class="text-sm text-gray-500">
                <a href="#">@leonardkrasner</a>
              </p>
            </div>
            <div class="flex-shrink-0">
              <button
                type="button"
                class="inline-flex items-center px-3 py-0.5 rounded-full bg-rose-50 text-sm font-medium text-rose-700 hover:bg-rose-100"
              >
                <svg
                  class="-ml-1 mr-0.5 h-5 w-5 text-rose-400"
                  x-description="Heroicon name: solid/plus-sm"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  aria-hidden="true"
                >
                  <path
                    fill-rule="evenodd"
                    d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
                <span> Follow </span>
              </button>
            </div>
        </div> -->
      </div>
    </div>
  </section>
  {% endif %}
{% endblock right_section %}

templates/foro/post/list.html
{% extends 'base.html' %}